challenge_user:
    resource: "@ChallengeUserBundle/Controller/"
    type:     annotation
    prefix:   /

challenge_invitation:
    resource: "@ChallengeInvitationBundle/Controller/"
    type:     annotation
    prefix:   /invitation

app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin