services:
#    challenge_user.example:
#        class: ChallengeUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    challenge_user.admin.user:
        class: ChallengeUserBundle\Admin\UserAdmin
        arguments: [~, ChallengeUserBundle\Entity\User, ChallengeUserBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
        public: true
